name: Community Publish Package

on:
  push:
    tags:
      - '*'
#   release:
#     types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: 'Get Previous tag'
        id: previoustag
        uses: oprypin/find-latest-tag@v1
        with:
          repository: pragmatic-engineering/svelte-form-builder-pro
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@pragmatic-engineering'
      - run: |
          npm i
          npm run build
          cd package
          npm version ${{ steps.previoustag.outputs.tag }}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          scope: '@pragmatic-engineering'
      - run: |
          npm i
          npm run build
          cd package
          npm version ${{ steps.previoustag.outputs.tag }}
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      - name: Community Publish Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.AUTOMERGE }}
          repository: pragmatic-engineering/svelte-form-builder-pro
          event-type: community-publish
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "msg": "svelte-form-builder-community ${{steps.previoustag.outputs.tag}}"}'
