name: Publish Package

on:
  push:
    branches: ['master']
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@pragmatic-engineering'
      - run: |
          npm i
          npm run build
          cd package
          npm version prerelease --preid=rc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
